name: Run Vaccine Finder

on:
  push:
  schedule:
    - cron:  '10 3-18 * * *'

jobs:
  vaccine-script:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Script
      run: |
        python script.py
#     - name: Send mail
#       uses: dawidd6/action-send-mail@v3
#       with:
#         # Required mail server address:
#         server_address: smtp.gmail.com
#         # Required mail server port:
#         server_port: 465
#         # Required mail server username:
#         username: ${{secrets.MAIL_USERNAME}}
#         # Required mail server password:
#         password: ${{secrets.MAIL_PASSWORD}}
#         # Required mail subject:
#         subject: Github Actions job result
#         # Required recipients' addresses:
#         to: kaul.sarath@gmail.com
#         # Required sender full name (address can be skipped):
#         from: Vaccine Bot # <user@example.com>
#         # Optional whether this connection use TLS (default is true if server_port is 465)
#         secure: true
#         # Optional plain body:
#         body: Build job of ${{github.repository}} completed successfully!
#         # Optional HTML body read from file:
#         html_body: "Checking In"
#         ignore_cert: true
#         # Optional converting Markdown to HTML (set content_type to text/html too):
#         convert_markdown: true
#         # Optional attachments:
