name: Run Vaccine Finder

on:
#   push:
  # schedule:
  #   - cron:  '10 3-18 * * *'

jobs:
  vaccine-script:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#     - name: Install Express VPN
#       run: |
#           sudo wget https://www.expressvpn.works/clients/linux/expressvpn_3.7.0.29-1_amd64.deb
#           sudo dpkg -i expressvpn_3.7.0.29-1_amd64.deb
#     - name: Start Express VPN
#       run: |
#           sudo apt-get install expect
#           /usr/bin/expect <<EOD
#           spawn expressvpn activate 
#           expect "Enter activation code: "
#           send "${{ secrets.VPN_CODE }}\r"
#           expect "Activated"
#           EOD
#           expressvpn connect "India - Mumbai - 1"
#           expressvpn status
#     - name: Confirm IP location
#       run: |
#           curl ipinfo.io
    - name: Run Script
      run: |
        export SENDGRID_API_KEY=${{ secrets.API_KEY }}
        export PROXY=${{ secrets.PROXY }}
        python script.py
