name: Run Covid Stats

on:
#   push:
  workflow_dispatch:
#   schedule:
#     - cron:  '1/15 2-5,12-19 * * *'

jobs:
  stats-script:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Script
      run: |
        export ACC_SID=${{ secrets.ACC_SID }}
        export TOKEN=${{ secrets.TOKEN }}
        export RECEIVER=${{ secrets.RECEIVER }}
        export SENDER=${{ secrets.SENDER }}
        python covid_stats.py
    - name: Push DB JSON
      continue-on-error: true
      run: |
        git config --global user.name github-actions
        git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'          
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git commit -am "Pushed DB JSON"
        git push --force origin HEAD:$GITHUB_REF
