name: Run Covid Stats

on:
  push:
  # schedule:
  #   - cron:  '10 3-18 * * *'

jobs:
  stats-script:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Script
      run: |
        export ACC_SID=${{ secrets.ACC_SID }}
        export TOKEN=${{ secrets.TOKEN }}
        export RECEIVER=${{ secrets.RECEIVER }}
        export SENDER=${{ secrets.SENDER }}
        python covid_stats.py
